export type DodamTheme = Record<
  | "primaryNormal"
  | "primaryAlternative"
  | "primaryAssisitive"
  | "labelNormal"
  | "labelStrong"
  | "labelNetural"
  | "labelAlternative"
  | "labelAssisitive"
  | "labelDisabled"
  | "lineNormal"
  | "lineNetural"
  | "lineAlternative"
  | "fillNormal"
  | "fillNeutral"
  | "fillAlternative"
  | "fillAssistive"
  | "backgroundNormal"
  | "backgroundNetural"
  | "backgroundAlternative"
  | "statusNegative"
  | "statusCautionary"
  | "statusPositive"
  | "staticWhite"
  | "staticBlack",
  string
>;