name: 'Storybook Chromatic Docs Deployment'
on: push

jobs:
    chromatic:
        name: 'Run Chromatic'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - run: pnpm
            - uses: chromaui/action@latest
              with:
                projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                token: ${{ secrets.GIT_TOKEN }}